name: safe_spot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  geolocator: ^10.1.0
  permission_handler: ^12.0.1
  supabase_flutter: ^2.9.1
  image_picker: ^1.1.2
  url_launcher: ^6.1.14
  path: ^1.8.3
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter:
  uses-material-design: true
  assets:
    - assets/app1_icon.png
    - assets/bg2_icon.jpg
    - assets/bg3_icon.jpg
    - assets/bg4_icon.jpg
    - assets/bg5_icon.jpg
    - assets/bg6_icon.jpg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app1_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#4CAF50"
  image: assets/app1_icon.png
  
  android_12:
    image: assets/app1_icon.png
    color: "#4CAF50"
    
  ios: true
  
  android_gravity: center
  ios_content_mode: center